version: "3"
services:
  lumen-benchmark-nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    ports:
      - "8811:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - lumen-benchmark-php
  lumen-benchmark-php:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge